<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="Teht8_Default" Theme="Teht7" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>Tehtävä 8</title>
</head>
<body>
    <form id="form1" runat="server">
    <div class="wrapper">
        <h1>Autokauppias Jinta-Rouppi</h1>
    
        <!-- Login-->
        <asp:Label ID="lbLoginTiedot" runat="server" Text="Tunnukset: jrouppi // salasana" />
        <br />
        <br />
        <asp:Login ID="UserLogin" runat="server"
            OnAuthenticate="UserLogin_Authenticate"
            OnLoginError="UserLogin_LoginError"
            OnLoggedIn="UserLogin_LoggedIn"
            RememberMeText="Remember me.">
        </asp:Login>
        <asp:Button ID="btnLogout" runat="server" Text="Logout"  OnClick="btnLogout_Click" />
        <br />
        <br />
        
        <!-- Sivu -->
        <asp:Button ID="addNew" class="myButton" runat="server" OnClick="addNew_Click" Text="Lisää uusi auto"/>
        <asp:Button ID="saveToFile" class="myButton" runat="server" OnClick="saveToFile_Click" Text="Tallenna tietokanta" />
        <br />
        <asp:Label ID="lbVirhe" class="error" runat="server" Text="" />
        <br />
        <br />
        <asp:GridView ID="autoNakyma" runat="server" AllowSorting="True" AllowPaging="True" PageSize="20" Width="350px"
            AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
            OnSorting="autoNakyma_Sort" 
            OnPageIndexChanging="autoNakyma_PageIndexChange" 
            OnRowCancelingEdit="autoNakyma_RowCancelEdit" 
            OnRowDeleting="autoNakyma_RowDelete" 
            OnRowEditing="autoNakyma_RowEdit" 
            OnRowUpdating="autoNakyma_RowUpdate"/>
    </div>
    </form>
</body>
</html>
