<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="Teht7_Default" Theme="Teht7" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Tehtävä 7</title>
</head>
<body>
    <form id="form1" runat="server">
    <div class="wrapper">
    <h1>Autokauppias Jinta-Rouppi</h1>
        <asp:Button ID="addNew" class="myButton" runat="server" OnClick="addNew_Click" Text="Lisää uusi auto"/>
    <br />
    <br />
    <asp:GridView ID="autoNakyma" runat="server" AllowSorting="True" AllowPaging="True" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        OnSorting="autoNakyma_Sort" OnPageIndexChanging="autoNakyma_PageIndexChange" OnRowCancelingEdit="autoNakyma_RowCancelEdit" 
        OnRowDeleting="autoNakyma_RowDelete" OnRowEditing="autoNakyma_RowEdit" OnRowUpdating="autoNakyma_RowUpdate" PageSize="20" Width="350px"/>
    </div>
    </form>
</body>
</html>
